### PR TITLE
foreach advanced directive implementation

### PR DESCRIPTION
**Pull request by orionstein**
This is an implementation of a simple foreach advanced directive. I know you had mentioned in Issue #31 that it may be more involved, but this could be an adequate solution. I believe this is still in the spirit of the tool.

The implementation is denoted by the syntax
```
<!-- @foreach $VAR in CONTEXT_VAR -->
    Content $VAR Content
<!-- @endfor -->
```
CONTEXT_VAR can be 

* A stringified Object 
    * JSON.stringify({'1': 'Val', '2': 'Val2'});
* An Array cast to String
    * ['Val','Val2'].toString()
* A hardcoded Object String 
    * "{'1': 'Val', '2': 'Val2'}"
* A hardcoded Array String 
    * "['Val','Val2']"

The Value of Each iteration can be injected using the $VAR keyword.

As a use case for this I have an Array of CDN links - ['link1','link2','link3']. 
Context is passed in as { SCRIPT_FILES: CDNArray.toString() }
This is preprocessed through this syntax -

```
<!-- @foreach $SCRIPT in SCRIPT_FILES -->
    <script src="$SCRIPT"></script>
<!-- @endfor -->
```

Which produces the set of Script sources.

Testing has been included with Array tests, Object Tests, and a Mix test group which tests including other Preprocess directives inside a looped template.

I hope this is appropriate, and look forward to hearing your thoughts on this.
Thank you very much!

### CODE REVIEW

**Comment by orionstein** [comment]
Also with an  Content 
Files that can be extended contain an  block that pulls in the content in the extend tags.

**Comment by orionstein** [comment]
@jsoverson, not sure if you are open to pull requests currently

**Comment by jsoverson** [comment]
Oh awesome. Sorry, this was off my radar. Do you want commit access to manage this directly? (/cc @BendingBender for the same question because of #52)

**Comment by orionstein** [comment]
Either way, if you want to pull it in that's fine, otherwise I can merge it if you are comfortable with that.

Thanks,  
     Orion

**Comment by jsoverson** [comment]
I added you @orionstein. I'm available for any guidance or help, I just don't want to be a blocker for people who are actively taking initiative.

**Comment by BendingBender** [comment]
@jsoverson, it would be great to have commit access.

**Comment by jsoverson** [comment]
add @BendingBender as well.

**Comment by jsoverson** [comment]
I can still publish to npm unless either of you want to take on that responsibility. If not, just open issues to publish version x.x.x.

**Comment by orionstein** [comment]
Once @BendingBender merges in their commits, we can open an issue to publish the updated version to npm.

Thanks,

**Comment by BendingBender** [comment]
Sorry, I'm on vacation right now, it might take me a few days to merge it
because I have a flaky internet connection here.
Am 04.06.2015 17:58 schrieb "Orion Free" <notifications@github.com>:

**Comment by BendingBender** [comment]
Ok, merged in my stuff, bumped project to v.2.3.0, added a tag and created an issue for @jsoverson to publish the lib to npm, see #60.

**Pull request merged**
